class_path: experiments.losses.JTFSTLoss
init_args:
  shape: 44100
  J: 12
  Q1: 8
  Q2: 2
#  J_fr: 3
  J_fr: 5
  Q_fr: 2
#  T: null
  T: 2048
#  F: null
  F: 1
  format_: joint
  p: 2
  #  use_log1p: false
  use_log1p: true
