seed_everything: 420

custom:
  project_name: scrapl
  model_name: scrapl_Jfr5_T2048_F1_saga_pwa_log1p_nogm_724k_1e-4t5
  dataset_name: mars_808_n681_b8_meso2048__probs_n_batches_1
  cpu_batch_size: 8
  use_wandb_cpu: false
  use_wandb_gpu: false

trainer:
  accelerator: gpu
  benchmark: false
  devices: [5]
  max_epochs: 50
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1

data:
  class_path: eval_808.data.WavDataModule
  init_args:
    batch_size: 8
    root_dir: ../data/808_dataset
    sr: 44100
    n_samples: 44100
    n_train: 425
    n_val: 128
    n_test: 128
    n_delta_per_item: 1
    delta_min: -2048
    delta_max: 2048
    shuffle_seed: 0
    num_workers: 8

model:
  class_path: eval_808.lightning.DDSP808LightingModule
  init_args:
    model: spectral_2dcnn_14p.yml
    synth: synth.yml
    fe: fe.yml
    loss_func: ../eval_808/scrapl_saga_pwa.yml
    scrapl_probs_path: ../data/theta_importance_sampling/eval_808/scrapl_Jfr5_T2048_F1_saga_pwa_log1p_nogm_724k_1e-4t5__mars_808_n681_b16_meso2048__probs__n_theta_14__n_params_88__n_batches_1__n_iter_20__min_prob_frac_0.0__param_agg_none__seed_420.pt
    use_p_loss: false
    feature_type: cqt
    cqt_eps: 1e-3

    run_name: scrapl_Jfr5_T2048_F1_saga_pwa_log1p_nogm_724k_1e-4t5__mars_808_n681_b8_meso2048__probs_n_batches_1

optimizer: ../opt/sgd_1e-4.yml

lr_scheduler:
  class_path: torch.optim.lr_scheduler.LinearLR
  init_args:
    start_factor: 1.0        # multiplier for initial lr (so 1.0 → 1e-4)
    end_factor: 0.1          # multiplier for final lr (so 0.1 → 1e-5)
    total_iters: 50          # number of epochs
