class_path: experiments.scrapl_loss.SCRAPLLoss
init_args:
  shape: 32768
  J: 12
  Q1: 8
  Q2: 2
  J_fr: 3
  Q_fr: 2
  T: null
  F: null
  p: 2
  grad_mult: 1e8
  use_pwa: false
  use_saga: true
  sample_all_paths_first: false
  n_theta: 2
  min_prob_frac: 0.0
  